version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

  node-app:
    build: .
    container_name: node-app
    ports:
      - '3100:3100'
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/mydatabase
